In [62]:
import numpy as np
import pandas as pd

In [19]:
lst = [1,2,3,4,5,6,7]
arr = np.array(lst)
display(lst)
display(arr)

[1, 2, 3, 4, 5, 6, 7]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
one = np.ones((2,5), dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
zeros = np.zeros((2,5), dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
full = np.full((2,5), 20, dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
eye = np.eye(9,9,-3, dtype=int)
display(one)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
lst1 = [1,2,3,4,5,6,7]
lst2 = [1,2,3,4,5,6,2]
arr1 = np.array(lst1)
arr2 = np.array(lst2)

display(arr1,arr2, arr1 ==arr2, arr1 & arr1)

array([1, 2, 3, 4, 5, 6, 7])

array([1, 2, 3, 4, 5, 6, 2, 9])

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [56]:
ranges = np.arange(0,20).reshape(5,4)
display(ranges)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
from numpy import random

In [174]:
sf = np.arange(0,20)
random.shuffle(sf)

sf_per = random.permutation(sf)
display(sf, sf_per)

array([ 6, 13, 16,  1,  2, 10, 11,  4,  7, 15, 18,  9, 17,  0, 12,  5, 14,
        3,  8, 19])

array([15,  5,  9, 13, 19,  8,  1, 14,  0, 10, 17, 12, 16,  6,  3, 11,  4,
       18,  7,  2])

In [182]:
ser = pd.Series([1,2,3,4,5], index=list('abcde'))
display(ser)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [194]:
pd.DataFrame([[1,2,3,4,5],[1,2,3,4,5]], index=list('ab'), columns=list('abcde'))

a  b  c  d  e
a  1  2  3  4  5
b  1  2  3  4  5

In [205]:
food = pd.read_csv("./amazonFood.csv")
display(food.tail(5))

ProductId          UserId  \
41705  B007IVE938  A3MDETK0D5UAIN   
41706  B00125NESM   AGGS9IPJDU6ML   
41707  B003M5W8ZK  A373MY0PQL9R41   
41708  B003M5W8ZK  A3U2QUKGA7CJOP   
41709  B005GXGAGY  A33AYVATA17JUR   

                                             productName  Score  \
41705                 Ajika Organic Rose Buds, 1.6-Ounce      1   
41706   JOHN BOOS FBLG7224 Table,Stainless,Shelf,72"x24"      5   
41707  Green Mountain Coffee - Unsweetened Black Iced...      5   
41708  Green Mountain Coffee - Unsweetened Black Iced...      1   
41709  LATE JULY CHIP MLTIGRN GRNMOJO ORG, 5.5 OZ, PK...      5   

                             Summary  \
41705           Not what I expected.   
41706                        Great!!   
41707          Black tea v Coca Cola   
41708     Never Received the product   
41709  Great taste - and gluten free   

                                                    Text  
41705  I certainly could do better by these if I just...  
41706  Table is 35 inches in height.  It is heavy dut...  
41707  I have been one of those people that always fe...  
41708  I was charged for this product by Liquid Natio...  
41709  Everyone in my family loves this chip - from t...

In [308]:
def find_userid(user_id):
    return 'A3' in user_id
    
def find_review(comment):
    return 'GOOD'.lower() in str(comment).lower()

good_comment = food[food['Summary'].apply(find_review)]
display(good_comment.tail(2))

#food[food['UserId'].apply(find_userid)]
#food[food['Summary'].apply(find_review)]

ProductId          UserId  \
41675  B0016B3R34  A2MKDOEB6K6KS1   
41681  B001M1YW0U  A29QCPFDSDNNKQ   

                                             productName  Score  \
41675  STARWEST BOTANICALS Tea Sencha leaf Tea Japan ...      5   
41681        Chex Corn Cereal, 14-Ounce Box (Pack of 14)      5   

                         Summary  \
41675            Tasting so good   
41681  Wow, so good and so cheap   

                                                    Text  
41675  This tea is high quality and the taste is fres...  
41681  It took me a bit to consider getting 14 boxes ...

In [314]:
# good_comment['UserId'].value_counts()

all_comment = food[food['UserId'] == "AY12DBB0U420B"]["UserId"].count()
goods = good_comment[good_comment['UserId'] == "AY12DBB0U420B"]["UserId"].count()

display(all_comment, goods)

38

15

## Answer

นำเข้าข้อมูล csv ชื่อไฟล์ว่า amazonFood.csv
และลอง นำออกมาแสดง 5 ตัวอย่าง

In [319]:
food = pd.read_csv("./amazonFood.csv")
food.tail(5)

ProductId          UserId  \
41705  B007IVE938  A3MDETK0D5UAIN   
41706  B00125NESM   AGGS9IPJDU6ML   
41707  B003M5W8ZK  A373MY0PQL9R41   
41708  B003M5W8ZK  A3U2QUKGA7CJOP   
41709  B005GXGAGY  A33AYVATA17JUR   

                                             productName  Score  \
41705                 Ajika Organic Rose Buds, 1.6-Ounce      1   
41706   JOHN BOOS FBLG7224 Table,Stainless,Shelf,72"x24"      5   
41707  Green Mountain Coffee - Unsweetened Black Iced...      5   
41708  Green Mountain Coffee - Unsweetened Black Iced...      1   
41709  LATE JULY CHIP MLTIGRN GRNMOJO ORG, 5.5 OZ, PK...      5   

                             Summary  \
41705           Not what I expected.   
41706                        Great!!   
41707          Black tea v Coca Cola   
41708     Never Received the product   
41709  Great taste - and gluten free   

                                                    Text  
41705  I certainly could do better by these if I just...  
41706  Table is 35 inches in height.  It is heavy dut...  
41707  I have been one of those people that always fe...  
41708  I was charged for this product by Liquid Natio...  
41709  Everyone in my family loves this chip - from t...

นำข้อมูลที่ได้จาการ นำเข้า มา

 - หาความยาวของข้อความ Summary ถ้าน้อยกว่า 5 คำ (แสดง 2 ตัวอย่าง)

In [338]:
def find_word(word):
    word = str(word)
    if len(word.split(" ")) < 5:
        return False
    else:
        return True
    
food[food['Summary'].apply(find_word)].tail(2)

ProductId          UserId  \
41707  B003M5W8ZK  A373MY0PQL9R41   
41709  B005GXGAGY  A33AYVATA17JUR   

                                             productName  Score  \
41707  Green Mountain Coffee - Unsweetened Black Iced...      5   
41709  LATE JULY CHIP MLTIGRN GRNMOJO ORG, 5.5 OZ, PK...      5   

                             Summary  \
41707          Black tea v Coca Cola   
41709  Great taste - and gluten free   

                                                    Text  
41707  I have been one of those people that always fe...  
41709  Everyone in my family loves this chip - from t...

 - จากข้อก่อนหน้ามีกี่คนที่ให้ 5 คะแนนที่คน

In [359]:
a = food[food['Summary'].apply(find_word)]
b = a[a['Score'] == 5]['UserId']
display(b.value_counts().count())

7241

 - แสดง top 5 product Name ทั้งหมด ที่ในชื่อมีคำว่า Coffee

In [356]:
food[food['productName'].apply(lambda x: 'coffee' in x.lower())]['productName'].value_counts().head()

54     Green Unroasted Mexican Altura, Whole Bean Cof...
55     Green Unroasted Mexican Altura, Whole Bean Cof...
139    International Delight Non-Dairy Hazelnut, 24 C...
159    Fantasicakes Gourmet Cinnamon Coffee Cake (8"/...
289    Berres Brothers Coffee Roasters Turtle Sundae ...
Name: productName, dtype: object

 - แสดงค่าเฉลี่ยคะแนนของคนที่ทานกาแฟ

In [362]:
food[food['productName'].apply(lambda x: 'coffee' in x.lower())]['Score'].mean()

4.131608548931384

 - แสดงจำนวนเมนูทั้งหมด ไม่นับชื่อเมนูที่ซ้ำกัน

In [369]:
len(food['productName'].unique())

4939