# จง slicing คำต่อไปนี้ "Sorrawit Nuernuam"

In [2]:
a ="Sorrawit Nuernuam"
print(a[0:5])

Sorra


Sorra


In [3]:
a ="Sorrawit Nuernuam"
print(a[1:8:2])

orwt


orwt


# จงหา Run ให้ได้ค่าดังนี้โดยใช้
a = ["pond","kuy",3,5,6]
b = {"Nahee":"Guy","Joy":3}
C = [1,2,3,6,5]

In [11]:
a = ["pond","kuy",3,5,6]
a.reverse()
a

[6, 5, 3, 'kuy', 'pond']

[6, 5, 3, 'kuy', 'pond']

In [13]:
a = ["pond","kuy",3,5,6]
a.insert(4,"John")
a

['pond', 'kuy', 3, 5, 'John', 6]

['pond', 'kuy', 3, 5, 'John', 6]

In [14]:
b = {"Nahee":"Guy","Joy":3}
print("Value is "+b.get("Nahee"))

Value is Guy


Value is Guy


In [16]:
C = [1,2,3,6,5]
C.sort()
C

[1, 2, 3, 5, 6]

[1, 2, 3, 5, 6]

## Numpy

In [6]:
#จง import numpy
import numpy as np

In [25]:
a = np.eye(5,10,-1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [25]:
#หาค่าด้วยการใช้ eye

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [27]:
from numpy import random as rd 
lst = [5,8,4,1]
a = rd.choice(lst,p=[0,0,0,1],size=[4,4])
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [34]:
from numpy import random as rd 
lst = [5,8,4,1]
#หาค่าด้วยการใช้ choice
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [28]:
a = np.array([1,2,5])
b = np.array([6])
c = a+b
print(c)

[ 7  8 11]


In [18]:
a = np.array([1,2,5])
b = np.array([6])
c =#หาค่าc
print(c)

[ 7  8 11]


In [29]:
d = np.arange(60).reshape(6,10)
print(d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [34]:
d = np.arange(60).reshape(6,10)
print(d[4,7])

47


In [28]:
#ใช้ array ต่อจากข้อก่อนหน้าแล้วหาค่า


47

In [38]:
a = np.arange(15)
print(a[2:9:3])

[2 5 8]


In [30]:
a = np.arange(15)
print()

[2 5 8]


In [59]:
d = np.arange(60).reshape(6,10)
print(d[4:7:,4:7:2])

[[44 46]
 [54 56]]


In [34]:
d = np.arange(60).reshape(6,10)
print()

[[44 46]
 [54 56]]


In [67]:
a = np.arange(20).reshape(5,4)
cond = [True,True,False,True,False]
print(a[cond])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]]


In [39]:
a = np.arange(20).reshape(5,4)

print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]]


In [68]:
arr1 = np.array([[3,6],[8,8]])
arr2 = np.array([[5,5],[7,8]])
arr = np.concatenate((arr1,arr2),axis =1 )
print(arr)

[[3 6 5 5]
 [8 8 7 8]]


In [42]:
arr1 = np.array([[3,6],[8,8]])
arr2 = np.array([[5,5],[7,8]])

print(arr)

[[3 6 5 5]
 [8 8 7 8]]


# Pandas

In [34]:
#import
import pandas as pd

In [71]:
#ให้นำเข้าข้อมูล
store = pd.read_excel('Sample - Superstore.xls')
store

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class   
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class   
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class   
...      ...             ...        ...        ...             ...   
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class   
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class   
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson   
1       CG-12520       Claire Gute   Consumer  United States        Henderson   
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles   
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale   
...          ...               ...        ...            ...              ...   
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami   
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa   
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs   
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables   
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage   
...   ...         ...     ...              ...              ...          ...   
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2   
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                        Eldon Fold 'N Roll Cart System   22.3680         2   
...                                                 ...       ...       ...   
9989                             Ultra Door Pull Handle   25.2480         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2   
9991                              Aastra 57i VoIP phone  258.5760         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.

In [72]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Row ID         9994 non-null   int64         
 1   Order ID       9994 non-null   object        
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object        
 5   Customer ID    9994 non-null   object        
 6   Customer Name  9994 non-null   object        
 7   Segment        9994 non-null   object        
 8   Country        9994 non-null   object        
 9   City           9994 non-null   object        
 10  State          9994 non-null   object        
 11  Postal Code    9994 non-null   int64         
 12  Region         9994 non-null   object        
 13  Product ID     9994 non-null   object        
 14  Category       9994 non-null   object        
 15  Sub-Category   9994 n

In [45]:
#ให้ใช้คำสั่ง info


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Row ID         9994 non-null   int64         
 1   Order ID       9994 non-null   object        
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object        
 5   Customer ID    9994 non-null   object        
 6   Customer Name  9994 non-null   object        
 7   Segment        9994 non-null   object        
 8   Country        9994 non-null   object        
 9   City           9994 non-null   object        
 10  State          9994 non-null   object        
 11  Postal Code    9994 non-null   int64         
 12  Region         9994 non-null   object        
 13  Product ID     9994 non-null   object        
 14  Category       9994 non-null   object        
 15  Sub-Category   9994 n

In [74]:
store[store['City']=='Orem']

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
24        25  CA-2015-106320 2015-09-25 2015-09-30  Standard Class   
718      719  CA-2014-104472 2014-06-02 2014-06-07  Standard Class   
719      720  CA-2014-104472 2014-06-02 2014-06-07  Standard Class   
2558    2559  CA-2015-147788 2015-05-31 2015-06-04  Standard Class   
2559    2560  CA-2015-147788 2015-05-31 2015-06-04  Standard Class   
2560    2561  CA-2015-147788 2015-05-31 2015-06-04  Standard Class   
7707    7708  CA-2017-100237 2017-10-15 2017-10-19  Standard Class   
8796    8797  CA-2016-106397 2016-07-07 2016-07-13  Standard Class   
8797    8798  CA-2016-106397 2016-07-07 2016-07-13  Standard Class   

     Customer ID       Customer Name      Segment        Country  City  ...  \
24      EB-13870         Emily Burns     Consumer  United States  Orem  ...   
718     CK-12325  Christine Kargatis  Home Office  United States  Orem  ...   
719     CK-12325  Christine Kargatis  Home Office  United States  Orem  ...   
2558    TM-21010      Tamara Manning     Consumer  United States  Orem  ...   
2559    TM-21010      Tamara Manning     Consumer  United States  Orem  ...   
2560    TM-21010      Tamara Manning     Consumer  United States  Orem  ...   
7707    SV-20815          Stuart Van    Corporate  United States  Orem  ...   
8796    MJ-17740           Max Jones     Consumer  United States  Orem  ...   
8797    MJ-17740           Max Jones     Consumer  United States  Orem  ...   

     Postal Code  Region       Product ID         Category Sub-Category  \
24         84057    West  FUR-TA-10000577        Furniture       Tables   
718        84057    West  OFF-BI-10001658  Office Supplies      Binders   
719        84057    West  FUR-FU-10000246        Furniture  Furnishings   
2558       84057    West  FUR-BO-10004357        Furniture    Bookcases   
2559       84057    West  OFF-LA-10003766  Office Supplies       Labels   
2560       84057    West  OFF-ST-10000046  Office Supplies      Storage   
7707       84057    West  OFF-AR-10001761  Office Supplies          Art   
8796       84057    West  OFF-PA-10003441  Office Supplies        Paper   
8797       84057    West  OFF-AR-10004602  Office Supplies          Art   

                                        Product Name     Sales  Quantity  \
24     Bretford CR4500 Series Slim Rectangular Table  1044.630         3   
718                 GBC Standard Therm-A-Bind Covers    59.808         3   
719                          Aluminum Document Frame    73.320         6   
2558  O'Sullivan Living Dimensions 3-Shelf Bookcases  1406.860         7   
2559                  Self-Adhesive Removable Labels    15.750         5   
2560                Fellowes Super Stor/Drawer Files   323.100         2   
7707          Avery Hi-Liter Smear-Safe Highlighters    11.680         2   
8796                                       Xerox 226    12.960         2   
8797    Boston KS Multi-Size Manual Pencil Sharpener    45.980         2   

      Discount    Profit  
24         0.0  240.2649  
718        0.2   19.4376  
719        0.0   21.9960  
2558       0.0  140.6860  
2559       0.0    7.5600  
2560       0.0   61.3890  
7707       0.0    4.2048  
8796       0.0    6.2208  
8797       0.0   12.8744  

[9 rows x 21 columns]

In [69]:
#หาข้อมูลของ Orem City


Row ID        Order ID Order Date  Ship Date       Ship Mode  \
24        25  CA-2015-106320 2015-09-25 2015-09-30  Standard Class   
718      719  CA-2014-104472 2014-06-02 2014-06-07  Standard Class   
719      720  CA-2014-104472 2014-06-02 2014-06-07  Standard Class   
2558    2559  CA-2015-147788 2015-05-31 2015-06-04  Standard Class   
2559    2560  CA-2015-147788 2015-05-31 2015-06-04  Standard Class   
2560    2561  CA-2015-147788 2015-05-31 2015-06-04  Standard Class   
7707    7708  CA-2017-100237 2017-10-15 2017-10-19  Standard Class   
8796    8797  CA-2016-106397 2016-07-07 2016-07-13  Standard Class   
8797    8798  CA-2016-106397 2016-07-07 2016-07-13  Standard Class   

     Customer ID       Customer Name      Segment        Country  City  ...  \
24      EB-13870         Emily Burns     Consumer  United States  Orem  ...   
718     CK-12325  Christine Kargatis  Home Office  United States  Orem  ...   
719     CK-12325  Christine Kargatis  Home Office  United States  Orem  ...   
2558    TM-21010      Tamara Manning     Consumer  United States  Orem  ...   
2559    TM-21010      Tamara Manning     Consumer  United States  Orem  ...   
2560    TM-21010      Tamara Manning     Consumer  United States  Orem  ...   
7707    SV-20815          Stuart Van    Corporate  United States  Orem  ...   
8796    MJ-17740           Max Jones     Consumer  United States  Orem  ...   
8797    MJ-17740           Max Jones     Consumer  United States  Orem  ...   

     Postal Code  Region       Product ID         Category Sub-Category  \
24         84057    West  FUR-TA-10000577        Furniture       Tables   
718        84057    West  OFF-BI-10001658  Office Supplies      Binders   
719        84057    West  FUR-FU-10000246        Furniture  Furnishings   
2558       84057    West  FUR-BO-10004357        Furniture    Bookcases   
2559       84057    West  OFF-LA-10003766  Office Supplies       Labels   
2560       84057    West  OFF-ST-10000046  Office Supplies      Storage   
7707       84057    West  OFF-AR-10001761  Office Supplies          Art   
8796       84057    West  OFF-PA-10003441  Office Supplies        Paper   
8797       84057    West  OFF-AR-10004602  Office Supplies          Art   

                                        Product Name     Sales  Quantity  \
24     Bretford CR4500 Series Slim Rectangular Table  1044.630         3   
718                 GBC Standard Therm-A-Bind Covers    59.808         3   
719                          Aluminum Document Frame    73.320         6   
2558  O'Sullivan Living Dimensions 3-Shelf Bookcases  1406.860         7   
2559                  Self-Adhesive Removable Labels    15.750         5   
2560                Fellowes Super Stor/Drawer Files   323.100         2   
7707          Avery Hi-Liter Smear-Safe Highlighters    11.680         2   
8796                                       Xerox 226    12.960         2   
8797    Boston KS Multi-Size Manual Pencil Sharpener    45.980         2   

      Discount    Profit  
24         0.0  240.2649  
718        0.2   19.4376  
719        0.0   21.9960  
2558       0.0  140.6860  
2559       0.0    7.5600  
2560       0.0   61.3890  
7707       0.0    4.2048  
8796       0.0    6.2208  
8797       0.0   12.8744  

[9 rows x 21 columns]

In [75]:
store['Sales'].mean()

229.8580008304938

In [65]:
#หาค่าเฉลี่ยของ Sales


229.8580008304938

In [76]:
store[store['Category']=='Furniture']['Profit'].max()

1013.1270000000001

In [81]:
#หา Profit สูงสุดของ Furniture


1013.1270000000001

In [82]:
store.loc[store['Order ID']=='CA-2017-141446','Region']

9960    South
Name: Region, dtype: object

In [82]:
#หาข้อมูล region ของ CA-2017-141446


9960    South
Name: Region, dtype: object

In [83]:
store.loc[store['Order ID']=='CA-2017-141446','Customer ID']

9960    CL-12700
Name: Customer ID, dtype: object

In [83]:
#หาข้อมูล Customer ID ของ CA-2017-141446


9960    CL-12700
Name: Customer ID, dtype: object

In [85]:
store.groupby(['Region'])['Discount'].mean()

Region
Central    0.240353
East       0.145365
South      0.147253
West       0.109335
Name: Discount, dtype: float64

In [87]:
#จงหาค่าเฉลี่ยของ Discount ในแต่ละ Region


Region
Central    0.240353
East       0.145365
South      0.147253
West       0.109335
Name: Discount, dtype: float64

In [1]:
#Pandas(ต่อ)

In [10]:
a = np.arange(20).reshape(5,4)
df = pd.DataFrame(a,index='a b c d e'.split(),columns = 'V W X Y'.split())
df

V   W   X   Y
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19

In [7]:
#จงสร้าง DataFrame(เฉลยอยู่ล่างสุด)


V   W   X   Y
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19

In [12]:
df['Z'] = [1,2,3,4,5]
df

V   W   X   Y  Z
a   0   1   2   3  1
b   4   5   6   7  2
c   8   9  10  11  3
d  12  13  14  15  4
e  16  17  18  19  5

In [8]:
#จงเพิ่ม Columns Z ลงไป กำหนดค่าเป็น 1,2,3,4,5


V   W   X   Y  Z
a   0   1   2   3  1
b   4   5   6   7  2
c   8   9  10  11  3
d  12  13  14  15  4
e  16  17  18  19  5

In [14]:
df.loc['f'] = [6,7,8,9,10]
df

V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c   8   9  10  11   3
d  12  13  14  15   4
e  16  17  18  19   5
f   6   7   8   9  10

In [9]:
#จงเพิ่ม Index f ลงไป กำหนดค่าเป็น 6,7,8,9,10


V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c   8   9  10  11   3
d  12  13  14  15   4
e  16  17  18  19   5
f   6   7   8   9  10

In [17]:
len(df.columns)

5

In [11]:
#จงแสดงจำนวน Columns ทั้งหมด


5

In [18]:
df.loc['c'] =[8,0,0,0,3]
df.loc['d'] =[12,0,0,0,4]
df

V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c   8   0   0   0   3
d  12   0   0   0   4
e  16  17  18  19   5
f   6   7   8   9  10

In [12]:
#เปลี่ยนตัวเลข 6 ตัวตรงกลางให้เป็น 0


V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c   8   0   0   0   3
d  12   0   0   0   4
e  16  17  18  19   5
f   6   7   8   9  10

In [40]:
df['Sum'] = df['Y']+df['Z']
df

V   W   X   Y   Z  Sum
a   0   1   2   3   1    4
b   4   5   6   7   2    9
c   8   0   0   0   3    3
d  12   0   0   0   4    4
e  16  17  18  19   5   24
f   6   7   8   9  10   19

In [13]:
#สร้าง Columns 'Sum' มีค่าเป็นผลรวมของ 'Y' และ 'Z'


V   W   X   Y   Z  Sum
a   0   1   2   3   1    4
b   4   5   6   7   2    9
c   8   0   0   0   3    3
d  12   0   0   0   4    4
e  16  17  18  19   5   24
f   6   7   8   9  10   19

In [42]:
df.drop('Sum',axis=1,inplace = True)
df.drop('c',axis=0,inplace = True)
df

V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
d  12   0   0   0   4
e  16  17  18  19   5
f   6   7   8   9  10

In [14]:
#ทำการลบ Columns 'Sum' และ Index 'c' ออก และแสดงผลลัพธ์ออกมา (inplace = True)


V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
d  12   0   0   0   4
e  16  17  18  19   5
f   6   7   8   9  10

In [46]:
df.loc['e']

V    16
W    17
X    18
Y    19
Z     5
Name: e, dtype: int64

In [15]:
#จงแสดงค่าของ Index 'e'

V    16
W    17
X    18
Y    19
Z     5
Name: e, dtype: int64

In [47]:
df.rename(index = {'d':'c','e':'d','f':'e'},inplace = True)
df

V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c  12   0   0   0   4
d  16  17  18  19   5
e   6   7   8   9  10

In [16]:
#จงเปลี่ยนชื่อ Index 'd' เป็น 'c' , 'e' เป็น 'd' และ 'f' เป็น 'e' และแสดงผลลัพธ์ออกมา (inplace = True) 
df.rename(index = {'d':'c','e':'d','f':'e'},inplace = True)
df

V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c  12   0   0   0   4
d  16  17  18  19   5
e   6   7   8   9  10

In [48]:
df = pd.concat([df,df])
df

V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c  12   0   0   0   4
d  16  17  18  19   5
e   6   7   8   9  10
a   0   1   2   3   1
b   4   5   6   7   2
c  12   0   0   0   4
d  16  17  18  19   5
e   6   7   8   9  10

In [18]:
#จงนำ DataFrame จากข้อก่อนหน้ามารวมกันให้ได้ผลลัพธ์แบบด้นล่าง


V   W   X   Y   Z
a   0   1   2   3   1
b   4   5   6   7   2
c  12   0   0   0   4
d  16  17  18  19   5
e   6   7   8   9  10
a   0   1   2   3   1
b   4   5   6   7   2
c  12   0   0   0   4
d  16  17  18  19   5
e   6   7   8   9  10

In [49]:
df = pd.concat([df,df],axis = 1)
df

V   W   X   Y   Z   V   W   X   Y   Z
a   0   1   2   3   1   0   1   2   3   1
b   4   5   6   7   2   4   5   6   7   2
c  12   0   0   0   4  12   0   0   0   4
d  16  17  18  19   5  16  17  18  19   5
e   6   7   8   9  10   6   7   8   9  10
a   0   1   2   3   1   0   1   2   3   1
b   4   5   6   7   2   4   5   6   7   2
c  12   0   0   0   4  12   0   0   0   4
d  16  17  18  19   5  16  17  18  19   5
e   6   7   8   9  10   6   7   8   9  10

In [19]:
#จงนำ DataFrame จากข้อก่อนหน้ามารวมกันให้ได้ผลลัพธ์แบบด้นล่าง


V   W   X   Y   Z   V   W   X   Y   Z
a   0   1   2   3   1   0   1   2   3   1
b   4   5   6   7   2   4   5   6   7   2
c  12   0   0   0   4  12   0   0   0   4
d  16  17  18  19   5  16  17  18  19   5
e   6   7   8   9  10   6   7   8   9  10
a   0   1   2   3   1   0   1   2   3   1
b   4   5   6   7   2   4   5   6   7   2
c  12   0   0   0   4  12   0   0   0   4
d  16  17  18  19   5  16  17  18  19   5
e   6   7   8   9  10   6   7   8   9  10

In [ ]:
#เฉลยข้อบนนู้น
arr = np.arange(20).reshape(5,4)
df = pd.DataFrame(arr,
     index = 'a b c d e'.split() ,
     columns = list('VWXY'))
df